#!/usr/bin/python3
def eaise_exception_msg(message=""):
    raise NameError(message)
